name: Proto Generation Go

on:
  push:
    paths:
      - '**.proto'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21  # Adjust the Go version as needed

    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Install protoc-gen-go
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.25.0

    - name: Install protoc-gen-go-grpc
      run: |
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

    - name: Generate Go code from proto files
      run: |
        go mod download
        find . -name '*.proto' -exec protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative {} \;

    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Auto-generate Go code from proto files" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main  # Adjust the branch as needed
        github_token: ${{ secrets.GITHUB_TOKEN }}
