name: Proto Generation Swift

on:
  push:
    paths:
      - '**.proto'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install protoc for Swift
      run: |
        git clone https://github.com/apple/swift-protobuf.git
        cd swift-protobuf
        make install

    - name: Generate Swift code from proto files
      run: |
        find . -name '*.proto' -exec protoc --swift_out=. --swift_opt=Visibility=Public --swiftgrpc_out=. --swiftgrpc_opt=Visibility=Public {} \;

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto-generate Swift code from proto files" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}